import sys
from pathlib import Path

lines = []
lines.append('"""')
lines.append('tests/test_physics_benchmarks.py')
lines.append('')
lines.append('Physics benchmark validation tests for the BB84 QKD Simulator.')
lines.append('Validates QBER, channel attenuation, SKR, and binary entropy against')
lines.append('PHYSICS_CONTRACT.md benchmarks.')
lines.append('')
lines.append('Migrates all tests from test_physics.py (4 tests) and test_comprehensive.py')
lines.append('(14 tests) into proper pytest functions with descriptive assert messages.')
lines.append('')
lines.append('All stochastic tests use 5 independent trials and compare the mean against')
lines.append('the expected value.')
lines.append('"""')
lines.append('')
lines.append('import sys')
lines.append('from pathlib import Path')
lines.append('import numpy as np')
lines.append('import pytest')
lines.append('')
lines.append('_BACKEND_DIR = Path(__file__).parent.parent')
lines.append('if str(_BACKEND_DIR) not in sys.path:')
lines.append('    sys.path.insert(0, str(_BACKEND_DIR))')
lines.append('')
lines.append('from tests.conftest import run_pipeline, run_pipeline_trials, PipelineResult, TrialResult')
lines.append('from core.metrics import binary_entropy, compute_skr, compute_efficiency')
lines.append('from core.channel import QuantumChannel')
lines.append('from core.constants import DETECTOR_EFFICIENCY, ATTENUATION_COEFF_DB_PER_KM')
lines.append('from core.alice import Alice')
lines.append('from core.bob import Bob')
lines.append('from core.eve import Eve')
lines.append('from core.protocol import BB84Protocol')
lines.append('from core.wcp import poisson_photon_counts, classify_pulses')
lines.append('from core.decoy import assign_decoy_intensities')
lines.append('from core.pns import PNSAttack')

with open('tests/test_physics_benchmarks.py', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('Header written')
